using System.Text;
using System.Text.Json;
using Facturatix.Contracts.Recipes;

var fixturesDir = args[0];
var outputPath = Path.Combine(fixturesDir, "manifest.json");

var files = Directory.GetFiles(fixturesDir, "*.json")
    .Where(f => Path.GetFileName(f) != "manifest.json")
    .OrderBy(f => Path.GetFileName(f), StringComparer.Ordinal)
    .ToList();

var sb = new StringBuilder();
sb.AppendLine("{");
sb.AppendLine("  \"$comment\": \"GENERATED by tools/generate-manifest. Never hand-edit the hashes.\",");
sb.AppendLine("  \"schema\": \"recipe-execution.schema.v2.json\",");
sb.AppendLine("  \"schemaVersion\": 2,");
sb.AppendLine("  \"fixtures\": [");

for (var i = 0; i < files.Count; i++)
{
    var file = files[i];
    var json = File.ReadAllText(file);
    var result = RecipeSchemaV2Validator.Validate(json);
    var hash = RecipeCanonicalJson.ComputeHash(json);
    var codes = result.Codes;

    sb.AppendLine("    {");
    sb.AppendLine($"      \"file\": {JsonSerializer.Serialize(Path.GetFileName(file))},");
    sb.AppendLine($"      \"expectedValid\": {(result.IsValid ? "true" : "false")},");
    sb.Append("      \"expectedCodes\": [");
    sb.Append(string.Join(", ", codes.Select(c => JsonSerializer.Serialize(c))));
    sb.AppendLine("],");
    sb.AppendLine($"      \"canonicalHash\": \"{hash}\"");
    sb.Append(i == files.Count - 1 ? "    }" : "    },");
    sb.AppendLine();

    Console.WriteLine($"{Path.GetFileName(file),-42} valid={result.IsValid,-5} codes=[{string.Join(",", codes)}]");
    foreach (var issue in result.Issues)
    {
        Console.WriteLine($"    - {issue.Code} @ {issue.Path}: {issue.Message}");
    }
}

sb.AppendLine("  ]");
sb.AppendLine("}");

File.WriteAllText(outputPath, sb.ToString());
Console.WriteLine($"\nWrote {outputPath}");
